{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a7447279",
   "metadata": {},
   "source": [
    "# Automação de Sistemas e Processos com Python\n",
    "\n",
    "### Desafio:\n",
    "\n",
    "Para controle de custos, todos os dias, seu chefe pede um relatório com todas as compras de mercadorias da empresa.\n",
    "O seu trabalho, como analista, é enviar um e-mail para ele, assim que começar a trabalhar, com o total gasto, a quantidade de produtos compradas e o preço médio dos produtos.\n",
    "\n",
    "E-mail do seu chefe: para o nosso exercício, coloque um e-mail seu como sendo o e-mail do seu chefe<br>\n",
    "Link de acesso ao sistema da empresa: https://pages.hashtagtreinamentos.com/aula1-intensivao-sistema\n",
    "\n",
    "Para resolver isso, vamos usar o pyautogui, uma biblioteca de automação de comandos do mouse e do teclado"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "bb134a4e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pyautogui in c:\\users\\user\\anaconda3\\lib\\site-packages (0.9.53)\n",
      "Requirement already satisfied: mouseinfo in c:\\users\\user\\anaconda3\\lib\\site-packages (from pyautogui) (0.1.3)\n",
      "Requirement already satisfied: pymsgbox in c:\\users\\user\\anaconda3\\lib\\site-packages (from pyautogui) (1.0.9)\n",
      "Requirement already satisfied: PyTweening>=1.0.1 in c:\\users\\user\\anaconda3\\lib\\site-packages (from pyautogui) (1.0.4)\n",
      "Requirement already satisfied: pyscreeze>=0.1.21 in c:\\users\\user\\anaconda3\\lib\\site-packages (from pyautogui) (0.1.28)\n",
      "Requirement already satisfied: pygetwindow>=0.0.5 in c:\\users\\user\\anaconda3\\lib\\site-packages (from pyautogui) (0.0.9)\n",
      "Requirement already satisfied: pyrect in c:\\users\\user\\anaconda3\\lib\\site-packages (from pygetwindow>=0.0.5->pyautogui) (0.2.0)\n",
      "Requirement already satisfied: pyperclip in c:\\users\\user\\anaconda3\\lib\\site-packages (from mouseinfo->pyautogui) (1.8.2)\n"
     ]
    }
   ],
   "source": [
    "!pip install pyautogui"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca33d7af",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pyautogui\n",
    "from time import sleep\n",
    "\n",
    "# Passo a passo\n",
    "\n",
    "# pyautogui.click -> clique com o mouse\n",
    "# pyautogui.write -> escrever um texto\n",
    "# pyautogui.press -> apertar uma tecla\n",
    "# pyautogui.hotkey -> apertar uma combinação de teclas (ex: Ctrl + D)\n",
    "# pyautogui.position -> indica a posição do mouse (x, y)\n",
    "# pyautogui.PAUSE = seconds -> pausa entre comandos do pyautogui\n",
    "# pyperclip.copy() -> copiar o texto\n",
    "\n",
    "pyautogui.PAUSE = 1\n",
    "\n",
    "# Passo 1: Entrar no sistema da empresa(no link)\n",
    "pyautogui.hotkey('ctrl', 't')\n",
    "pyautogui.write(r'https://pages.hashtagtreinamentos.com/aula1-intensivao-sistema')\n",
    "pyautogui.press('enter')\n",
    "\n",
    "# pode ser que o navegador tenha que carregar\n",
    "sleep(3)\n",
    "\n",
    "# Passo 2: Fazer login\n",
    "# clicar no espaço de login\n",
    "pyautogui.click(x=942, y=373)\n",
    "\n",
    "# escrever login\n",
    "pyautogui.write('felipe_login')\n",
    "\n",
    "# clicar no espaço de senha\n",
    "pyautogui.click(x=948, y=457)\n",
    "\n",
    "# escrever senha\n",
    "pyautogui.write('felipesenha123')\n",
    "\n",
    "# clicar no botão acessar\n",
    "pyautogui.click(x=971, y=527)\n",
    "\n",
    "sleep(2)\n",
    "\n",
    "# Passo 3: Exportar a base de dados\n",
    "# clicar em cima do arquivo\n",
    "pyautogui.click(x=380, y=416)\n",
    "\n",
    "# clicar nos 3 pontinhos\n",
    "pyautogui.click(x=1714, y=186)\n",
    "\n",
    "# clicar em download\n",
    "pyautogui.click(x=1501, y=594)\n",
    "sleep(3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2131fd9d",
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "a4cc91ea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Point(x=1501, y=594)\n"
     ]
    }
   ],
   "source": [
    "sleep(5)\n",
    "print(pyautogui.position())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "ab5eb42f",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>CódigoCompra</th>\n",
       "      <th>Data</th>\n",
       "      <th>Fornecedor</th>\n",
       "      <th>Produto</th>\n",
       "      <th>Quantidade</th>\n",
       "      <th>ValorUnitário</th>\n",
       "      <th>ValorFinal</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>65014</td>\n",
       "      <td>01/12/2023</td>\n",
       "      <td>Fabrica Hashtag Brasil</td>\n",
       "      <td>Óleo Motor - Linha A</td>\n",
       "      <td>5</td>\n",
       "      <td>259.00</td>\n",
       "      <td>1295.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>65014</td>\n",
       "      <td>01/12/2023</td>\n",
       "      <td>Fabrica Hashtag Brasil</td>\n",
       "      <td>Kit Embreagem - Linha A</td>\n",
       "      <td>1</td>\n",
       "      <td>380.00</td>\n",
       "      <td>380.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>65016</td>\n",
       "      <td>01/12/2023</td>\n",
       "      <td>Fabrica Doidona Brasil</td>\n",
       "      <td>Bateria - Linha A</td>\n",
       "      <td>2</td>\n",
       "      <td>479.00</td>\n",
       "      <td>958.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>65016</td>\n",
       "      <td>01/12/2023</td>\n",
       "      <td>Fabrica Doidona Brasil</td>\n",
       "      <td>Filtro de Óleo - Linha A</td>\n",
       "      <td>1</td>\n",
       "      <td>18.90</td>\n",
       "      <td>18.90</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>65017</td>\n",
       "      <td>01/12/2023</td>\n",
       "      <td>Original Fábrica Brasil</td>\n",
       "      <td>Farol Principal - Linha A</td>\n",
       "      <td>3</td>\n",
       "      <td>159.90</td>\n",
       "      <td>479.70</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4538</th>\n",
       "      <td>69996</td>\n",
       "      <td>26/12/2023</td>\n",
       "      <td>Revenda Argentina</td>\n",
       "      <td>Logo Hashtag - Linha A</td>\n",
       "      <td>2</td>\n",
       "      <td>10.00</td>\n",
       "      <td>20.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4539</th>\n",
       "      <td>69996</td>\n",
       "      <td>26/12/2023</td>\n",
       "      <td>Revenda Argentina</td>\n",
       "      <td>Terminal de Direção - Linha B</td>\n",
       "      <td>4</td>\n",
       "      <td>156.40</td>\n",
       "      <td>625.60</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4540</th>\n",
       "      <td>69996</td>\n",
       "      <td>26/12/2023</td>\n",
       "      <td>Revenda Argentina</td>\n",
       "      <td>Farol Principal - Linha B</td>\n",
       "      <td>1</td>\n",
       "      <td>183.89</td>\n",
       "      <td>183.89</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4541</th>\n",
       "      <td>69997</td>\n",
       "      <td>26/12/2023</td>\n",
       "      <td>Fabrica Doidona Mexico</td>\n",
       "      <td>Pneus - Linha A</td>\n",
       "      <td>1</td>\n",
       "      <td>359.91</td>\n",
       "      <td>359.91</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4542</th>\n",
       "      <td>69997</td>\n",
       "      <td>26/12/2023</td>\n",
       "      <td>Fabrica Doidona Mexico</td>\n",
       "      <td>Kit Embreagem - Linha C</td>\n",
       "      <td>2</td>\n",
       "      <td>502.55</td>\n",
       "      <td>1005.10</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>4543 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      CódigoCompra        Data               Fornecedor  \\\n",
       "0            65014  01/12/2023   Fabrica Hashtag Brasil   \n",
       "1            65014  01/12/2023   Fabrica Hashtag Brasil   \n",
       "2            65016  01/12/2023   Fabrica Doidona Brasil   \n",
       "3            65016  01/12/2023   Fabrica Doidona Brasil   \n",
       "4            65017  01/12/2023  Original Fábrica Brasil   \n",
       "...            ...         ...                      ...   \n",
       "4538         69996  26/12/2023        Revenda Argentina   \n",
       "4539         69996  26/12/2023        Revenda Argentina   \n",
       "4540         69996  26/12/2023        Revenda Argentina   \n",
       "4541         69997  26/12/2023   Fabrica Doidona Mexico   \n",
       "4542         69997  26/12/2023   Fabrica Doidona Mexico   \n",
       "\n",
       "                            Produto  Quantidade  ValorUnitário  ValorFinal  \n",
       "0              Óleo Motor - Linha A           5         259.00     1295.00  \n",
       "1           Kit Embreagem - Linha A           1         380.00      380.00  \n",
       "2                 Bateria - Linha A           2         479.00      958.00  \n",
       "3          Filtro de Óleo - Linha A           1          18.90       18.90  \n",
       "4         Farol Principal - Linha A           3         159.90      479.70  \n",
       "...                             ...         ...            ...         ...  \n",
       "4538         Logo Hashtag - Linha A           2          10.00       20.00  \n",
       "4539  Terminal de Direção - Linha B           4         156.40      625.60  \n",
       "4540      Farol Principal - Linha B           1         183.89      183.89  \n",
       "4541                Pneus - Linha A           1         359.91      359.91  \n",
       "4542        Kit Embreagem - Linha C           2         502.55     1005.10  \n",
       "\n",
       "[4543 rows x 7 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "7254196.58\n",
      "9715\n",
      "746.70\n"
     ]
    }
   ],
   "source": [
    "# Passo 4: Calcular os indicadores\n",
    "import pandas as pd\n",
    "\n",
    "tabela = pd.read_csv(r'C:\\Users\\User\\Desktop\\INTENSIVAOpython\\PROJETO1\\Compras.csv', sep=';')\n",
    "display(tabela)\n",
    "\n",
    "total_gasto = tabela['ValorFinal'].sum()\n",
    "qtd = tabela['Quantidade'].sum()\n",
    "preco_medio = total_gasto / qtd\n",
    "\n",
    "print(total_gasto)\n",
    "print(qtd)\n",
    "print(f'{preco_medio:.2f}')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "id": "c53e2956",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pyperclip\n",
    "# Passo 5: Enviar um e-mail para o meu chefe\n",
    "\n",
    "pyautogui.PAUSE = 1\n",
    "\n",
    "# entrar no email: https://mail.google.com/mail/u/0/#inbox\n",
    "pyautogui.hotkey('ctrl', 't')\n",
    "pyautogui.write(r'https://mail.google.com/mail/u/0/#inbox')\n",
    "pyautogui.press('enter')\n",
    "\n",
    "sleep(3)\n",
    "\n",
    "# clicar no botão escrever\n",
    "pyautogui.click(x=43, y=207)\n",
    "\n",
    "# preencher as informações do email\n",
    "# destinatário\n",
    "pyautogui.write(r'pikatofly17@gmail.com')\n",
    "pyautogui.press('tab') # escolher o destinatário\n",
    "\n",
    "pyautogui.press('tab') # passar para o campo assunto\n",
    "pyperclip.copy('Relatório de Compras') # copia o texto\n",
    "pyautogui.hotkey('ctrl', 'v')\n",
    "\n",
    "pyautogui.press('tab') # passando para o corpo do email\n",
    "pyautogui.write('')\n",
    "\n",
    "\n",
    "# enviar\n",
    "# pyautogui.hotkey('ctrl', 'enter')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "id": "7f9a0629",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Point(x=1329, y=579)"
      ]
     },
     "execution_count": 63,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "sleep(5)\n",
    "pyautogui.position()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5099db46",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
